LibraryWebApp/LibraryWebApp/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using Repository;
using Repository.Models;

namespace LibraryWebApp.Controllers
{
    public class BooksController : Controller
    {
        /// <summary>
        /// Gets a list of all books, sorts the list and returns it to view
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            List<Book> books = BookRepository.GetBooks();
            Repository.Models.SortBooksByTitle sortBooksByTitle = new SortBooksByTitle();
            books.Sort(sortBooksByTitle);
            return View(books);
        }

        /// <summary>
        /// Gets a book by book id and returns it to view
        /// </summary>
        /// <param name="id"></param>
        /// <returns>a book to view</returns>
        public ActionResult Details(string id)
        {
            ObjectId bookId = new ObjectId(id);
            Book book = BookRepository.GetBookById(bookId);
            return View(book);
        }

        /// <summary>
        /// Shows create form
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Gets all value of a new book and creates it in db
        /// </summary>
        /// <param name="title"></param>
        /// <param name="genre"></param>
        /// <param name="author"></param>
        /// <param name="publishedYear"></param>
        /// <param name="copies"></param>
        /// <returns>Index</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string title, string genre, string author, string publishedYear, int copies)
        {
            try
            {
                if (title!=null)
                {
                    if (author!=null)
                    {
                        Book book = new Book(title, genre, copies, author, publishedYear);
                        BookRepository.CreateBook(book);

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["textmsg"] = "<script>alert('You have to select an author name');</script>";
                        return View();
                    }
                }
                else
                {
                    TempData["textmsg"] = "<script>alert('You have to select a title name');</script>";
                    return View();
                }
                
            }
            catch
            {
                return RedirectToAction("Edit");
            }
        }

        /// <summary>
        /// Gets a film by id from db and returns it to view
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(string id)
        {
            ObjectId bookId = new ObjectId(id);
            Book book = BookRepository.GetBookById(bookId);
            return View(book);
        }

        /// <summary>
        /// Gets new values of the book and updates it in db
        /// </summary>
        /// <param name="id"></param>
        /// <param name="title"></param>
        /// <param name="genre"></param>
        /// <param name="author"></param>
        /// <param name="publishedYear"></param>
        /// <param name="copies"></param>
        /// <returns>to index</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, string title, string genre, string author, string publishedYear, int copies)
        {
            try
            {
                ObjectId bookId = new ObjectId(id);
                Book book = new Book(title, genre, copies, author, publishedYear);
                book.Id = bookId;
                BookRepository.UpdateBook(book);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        /// Gets a film by id from db and returns it to view
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(string id)
        {
            ObjectId bookId = new ObjectId(id);
            Book book = BookRepository.GetBookById(bookId);
            return View(book);
        }

        /// <summary>
        /// Deletes the film from db
        /// </summary>
        /// <param name="id"></param>
        /// <returns>To index</returns>
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            try
            {
                ObjectId bookId = new ObjectId(id);
                BookRepository.DeleteBookById(bookId);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
    }
}

LibraryWebApp/LibraryWebApp/Controllers/RentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using Repository;
using Repository.Models;

namespace LibraryWebApp.Controllers
{
    public class RentsController : Controller
    {
        /// <summary>
        /// Gets a list of all rents from db, sorts the list by member name and returns to view
        /// </summary>
        /// <returns>a list of all rents</returns>
        public ActionResult Index()
        {
            List<Rent> rents = RentRepository.GetRents();
            SortRentsByMemberName sortRentsByMemberName = new SortRentsByMemberName();
            rents.Sort(sortRentsByMemberName);
            return View(rents);
        }

        /// <summary>
        /// Gets all rents of a member by member id from db and returns to view
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult MemberRents(string id)
        {
            ObjectId memberId = new ObjectId(id);
            List<Rent> rents = RentRepository.GetRentsByMemberId(memberId);
            return View(rents);
        }


        /// <summary>
        /// Gets a list of all rents of a book by book id from db, sorts the list and returns to view
        /// </summary>
        /// <param name="id"></param>
        /// <returns>A list of all rents of a book</returns>
        [Route("/Rents/BookRents/{id}")]
        public ActionResult BookRents(string id)
        {
            ObjectId bookId = new ObjectId(id);
            Book book = BookRepository.GetBookById(bookId);
            List<Rent> rents = RentRepository.GetAllSameBookRented(book);

            return View(rents);
        }

        /// <summary>
        /// Gets a list of all rents of a film by film id from db, sorts the list and returns to view
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Route("/Rents/FilmRents/{id}")]
        public ActionResult FilmRents(string id)
        {
            ObjectId filmId = new ObjectId(id);
            Film film = FilmRepository.GetFilmById(filmId);
            List<Rent> rents = RentRepository.GetAllSameFilmRented(film);

            return View(rents);
        }


        /// <summary>
        /// Gets a list of all books from db, sorts the list and returns to view
        /// </summary>
        /// <param name="id"></param>
        /// <returns>A list of all </returns>
        [Route("/Rents/RentBook/{id}")]
        public ActionResult RentBook(string id)
        {
            List<Book> books = BookRepository.GetBooks();
            SortBooksByTitle sortBooksByTitle = new SortBooksByTitle();
            books.Sort(sortBooksByTitle);
            return View(books);
        }

        /// <summary>
        /// Gets value of all rent object, checks the dates and creates a rent if all is correct
        /// </summary>
        /// <param name="id"></param>
        /// <param name="bookId"></param>
        /// <param name="startDate"></param>
        /// <param name="endDate"></param>
        /// <returns>If dates are not correct return a list of books to view</returns>
        [HttpPost]
        [Route("/Rents/RentBook/{id}")]
        public ActionResult RentBook(string id, string bookId, DateTime startDate, DateTime endDate)
        {
            List<Book> books = BookRepository.GetBooks();
            SortBooksByTitle sortBooksByTitle = new SortBooksByTitle();
            books.Sort(sortBooksByTitle);

            if (RentRepository.IsStartDateCorrect(startDate))
            {
                if (RentRepository.IsEndDateCorrect(endDate,startDate))
                {
                    ObjectId memberId = new ObjectId(id);
                    Member member = MemberRepository.GetMemberById(memberId);

                    ObjectId rentingBookId = new ObjectId(bookId);
                    Book book = BookRepository.GetBookById(rentingBookId);

                    Rent rent = new Rent(member, book, null, startDate, endDate);

                    if (BookRepository.BookIsFreeToRent(rent))
                    {
                        RentRepository.CreateRent(rent);
                        return Redirect($"/Rents/MemberRents/{id}");
                    }
                    else
                    {
                        TempData["textmsg"] = "<script>alert('This book is not free to Rent in this entered date period. Please try another dates');</script>";
                        return View(books);
                    }
                }
                else
                {
                    TempData["textmsg"] = "<script>alert('You entered a date before rent start date. Please try a date after rent start date');</script>";
                    return View(books);
                }
            }
            else
            {
                TempData["textmsg"] = "<script>alert('You entered a date before today date. Please try a date after today date');</script>";
                return View(books);
            }  
        }


        /// <summary>
        /// Gets a list of all films, sorts the list and returns to view
        /// </summary>
        /// <returns>A list of films</returns>
        [Route("/Rents/RentFilm/{id}")]
        public ActionResult RentFilm()
        {
            List<Film> films = FilmRepository.GetFilms();
            SortFilmsByTitle sortFilmsByTitle = new SortFilmsByTitle();
            films.Sort(sortFilmsByTitle);
            return View(films);
        }

        /// <summary>
        /// Gets value of all rent object, checks the dates and creates a rent if all is correct
        /// </summary>
        /// <param name="id"></param>
        /// <param name="filmId"></param>
        /// <param name="startDate"></param>
        /// <param name="endDate"></param>
        /// <returns>If dates are not correct return a list of films to view</returns>
        [HttpPost]
        [Route("/Rents/RentFilm/{id}")]
        public ActionResult RentFilm(string id, string filmId, DateTime startDate, DateTime endDate)
        {
            List<Film> films = FilmRepository.GetFilms();
            SortFilmsByTitle sortFilmsByTitle = new SortFilmsByTitle();
            films.Sort(sortFilmsByTitle);

            if (RentRepository.IsStartDateCorrect(startDate))
            {
                if (RentRepository.IsEndDateCorrect(endDate,startDate))
                {
                    ObjectId memberId = new ObjectId(id);
                    Member member = MemberRepository.GetMemberById(memberId);

                    ObjectId rentingFilmId = new ObjectId(filmId);
                    Film film = FilmRepository.GetFilmById(rentingFilmId);

                    Rent rent = new Rent(member, null, film, startDate, endDate);

                    if (FilmRepository.FilmIsFreeToRent(rent))
                    {

                        RentRepository.CreateRent(rent);
                        return Redirect($"/Rents/MemberRents/{id}");
                    }
                    else
                    {
                        TempData["textmsg"] = "<script>alert('This film is not free to Rent in this entered date period. Please try another dates');</script>";
                        return View(films);
                    }
                }
                else
                {
                    TempData["textmsg"] = "<script>alert('You entered a date before rent start date. Please try a date after rent start date');</script>";
                    return View(films);
                }
            }
            else
            {
                TempData["textmsg"] = "<script>alert('You entered a date before today date. Please try a date after today date');</script>";
                return View(films);
            }  
        }


        /// <summary>
        /// Gets a list of all members from db, sorts the list and returns to view
        /// </summary>
        /// <returns> a list of all members </returns>
        [Route("/Rents/RentBookToMember/{id}")]
        public ActionResult RentBookToMember()
        {
            List<Member> members = MemberRepository.GetMembers();
            SortMemberByName sortMemberByName = new SortMemberByName();
            members.Sort(sortMemberByName);
            return View(members);
        }


        /// <summary>
        /// Gets value of all rent object, checks the dates and creates a rent if all is correct
        /// </summary>
        /// <param name="id"></param>
        /// <param name="memberId"></param>
        /// <param name="startDate"></param>
        /// <param name="endDate"></param>
        /// <returns>If dates are not correct return a list of members to view</returns>
        [HttpPost]
        [Route("/Rents/RentBookToMember/{id}")]
        public ActionResult RentBookToMember(string id, string memberId, DateTime startDate, DateTime endDate)
        {
            List<Member> members = MemberRepository.GetMembers();
            SortMemberByName sortMemberByName = new SortMemberByName();
            members.Sort(sortMemberByName);

            if (RentRepository.IsStartDateCorrect(startDate))
            {
                if (RentRepository.IsEndDateCorrect(endDate, startDate))
                {
                    ObjectId RentingMemberId = new ObjectId(memberId);
                    Member member = MemberRepository.GetMemberById(RentingMemberId);

                    ObjectId rentingBookId = new ObjectId(id);
                    Book book = BookRepository.GetBookById(rentingBookId);

                    Rent rent = new Rent(member, book, null, startDate, endDate);

                    if (BookRepository.BookIsFreeToRent(rent))
                    {
                        RentRepository.CreateRent(rent);
                        return Redirect($"/Rents/MemberRents/{memberId}");
                    }

LibraryWebApp/LibraryWebApp/Views/Books/Create.cshtml
@model Repository.Models.Book

@{
    ViewData["Title"] = "Create";
}

@if (TempData["textmsg"] != null)
{
    @Html.Raw(TempData["textmsg"])
}

<h1>Create a new Book</h1>
<hr />
<p>* obligatory</p>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label">*Title</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label">*Author</label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishedYear" class="control-label"></label>
                <input asp-for="PublishedYear" class="form-control" />
                <span asp-validation-for="PublishedYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Copies" class="control-label">*Copies</label>
                <input asp-for="Copies" class="form-control" />
                <span asp-validation-for="Copies" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryWebApp/LibraryWebApp/Views/Books/Delete.cshtml
@model Repository.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublishedYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublishedYear)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Copies)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Copies)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" name="Id" value="@Model.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LibraryWebApp/LibraryWebApp/Views/Books/Details.cshtml
@model Repository.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishedYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishedYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Copies)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Copies)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id}) |
    <a asp-action="Index">Back to List</a>
</div>

LibraryWebApp/LibraryWebApp/Views/Books/Edit.cshtml
@model Repository.Models.Book

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" value="@Model.Title" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" value="@Model.Author" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" value="@Model.Genre"/>
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishedYear" class="control-label"></label>
                <input asp-for="PublishedYear" class="form-control" value="@Model.PublishedYear"/>
                <span asp-validation-for="PublishedYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Copies" class="control-label"></label>
                <input asp-for="Copies" class="form-control" value="@Model.Copies"/>
                <span asp-validation-for="Copies" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" name="Id" value="@Model.Id" />
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryWebApp/LibraryWebApp/Views/Books/Index.cshtml
@model IEnumerable<Repository.Models.Book>

@{
    ViewData["Title"] = "Index";
}

    <h1>List of all Books sorted by Title</h1>

    <style>
        .Delete {color: red}

        .Rent {color: black}
    </style>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Copies)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Copies)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "Delete" }) |
                    @Html.ActionLink("See all rents", "BookRents","Rents", new { id = item.Id }, new { @class = "Rent" }) |
                    @Html.ActionLink("Rent this Book", "RentBookToMember", "Rents", new { id = item.Id }, new { @class = "Rent" })
                </td>
            </tr>
        }
    </tbody>
</table>
@Html.ActionLink("Go back to home", "Index", "Home")